/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file is automatically generated and managed by Next.js.
// Do not edit it by hand — it will be re-created when you run `npm run dev`.
